# Generated by Django 2.0.3 on 2018-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarddata',
            name='added',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='end_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='impact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='intensity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='likelihood',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='published',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='relevance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='start_year',
            field=models.CharField(max_length=10),
        ),
    ]
